
import img12 from '/src/Images/12.jpg';
import img5 from '/src/Images/5.jpg';
import img6 from '/src/Images/6.jpg';
import img7 from '/src/Images/7.jpg';
import img8 from '/src/Images/8.jpg';


export const SValue = [
  {
    id: 'abdur-rahim',
    name: 'ABDUR RAHIM',
    role: 'Office Assistant',
    phone: '+8801885374041',
    email: '',
    photo: img12,
    mpoIndexNo: '-',
    joiningDate: '16 Jan, 2024',
    fathersName: 'ABUL BASHAR',
    mothersName: 'SAMSUN NAHAR',
    contactNo: '+8801885374041',
    nationalIdNo: '8670048449',
    qualification: 'MSc in Mathematics',
    experience: '',
    interest: '',
    presentAddress: 'Humayon Rashid Chattar, Sylhet',
    permanentAddress: 'Purba Jaflong, Gowainghat, Sylhet',
  },
  {
    id: 'nipendro-tasha',
    name: 'NIPENDRO TASHA',
    role: 'Office Assistant',
    phone: '+8801885374041',
    email: '',
    photo: img5,
    mpoIndexNo: '-',
    joiningDate: '',
    fathersName: '',
    mothersName: '',
    contactNo: '+8801885374041',
    nationalIdNo: '',
    qualification: '',
    experience: '',
    interest: '',
    presentAddress: '',
    permanentAddress: '',
  },
  {
    id: 'mohammad-delwar-hossain',
    name: 'MOHAMMAD DELWAR HOSSAIN',
    role: 'Office Assistant',
    phone: '+8801885374041',
    email: 'hmdelwar2356@gmail.com',
    photo: img6,
    mpoIndexNo: '-',
    joiningDate: '28 Feb, 2004',
    fathersName: 'MOHAMMAD ABDUL JABBAR',
    mothersName: 'MAFIYA KHATUN',
    contactNo: '+8801885374041',
    nationalIdNo: '19791911875715436',
    qualification: 'B.COM',
    experience: '',
    interest: '',
    presentAddress: 'HOUSE NO:71, ROAD NO: 44, BLOCK: c, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'VILL: BARESWAR, POST: BARESWAR, P.S: BURICHONG, DIST: COMILA',
  },
  {
    id: 'mira-rani-dahs',
    name: 'MIRA RANI DAHS',
    role: 'AYAH',
    phone: '+8801885374041',
    email: '',
    photo: img7,
    mpoIndexNo: '-',
    joiningDate: '03 Aug, 2008',
    fathersName: 'RANA DASH',
    mothersName: 'BINA RANI DASH',
    contactNo: '+8801753487483',
    nationalIdNo: '7800845724',
    qualification: '8th CLASS',
    experience: '',
    interest: '',
    presentAddress: 'BADRUL MIAR BASA, GOTATIKOR, POST: KODOMTOLI, THANA: DAKKHIN SURMA, ZILLA: SYLHET',
    permanentAddress: 'VILL: SURJOPASHA, PO: SOMSERGONJBAZAR, THANA+ZILLA: MOULVIBAZAR',
  },
  {
    id: 'chomok-tara',
    name: 'CHOMOK TARA',
    role: 'AYAH',
    phone: '+8801885374041',
    email: '',
    photo: img6,
    mpoIndexNo: '-',
    joiningDate: '',
    fathersName: '',
    mothersName: '',
    contactNo: '+8801885374041',
    nationalIdNo: '',
    qualification: '',
    experience: '',
    interest: '',
    presentAddress: '',
    permanentAddress: '',
  },
  {
    id: 'rakib-hasan',
    name: 'Rakib Hasan',
    role: 'NIGHT GIRD',
    phone: '+8801885374041',
    email: '',
    photo: img5,
    mpoIndexNo: '-',
    joiningDate: '',
    fathersName: '',
    mothersName: '',
    contactNo: '+8801885374041',
    nationalIdNo: '',
    qualification: '',
    experience: '',
    interest: '',
    presentAddress: '',
    permanentAddress: '',
  },
  {
    id: 'm-salim-ahmed',
    name: 'M. SALIM AHMED',
    role: 'PEON',
    phone: '+8801885374041',
    email: 'mdsalimahmed1979@gmail.com',
    photo: img8,
    mpoIndexNo: '-',
    joiningDate: '27 Jan, 1999',
    fathersName: 'LATE MD. JALAL UDDIN',
    mothersName: 'LATE JOYFUL BEGUM',
    contactNo: '+8801885374041',
    nationalIdNo: '9113523471651',
    qualification: 'H.S.C',
    experience: '',
    interest: '',
    presentAddress: 'BANGLADESH BANK SCHOOL,SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'VILL: SOTTISH, P/O: FENCHUGONJ, UP: FENCHUGONJ, DIST: SYLHET',
  },
  {
    id: 'sajjadur-rahman-sojib',
    name: 'SAJJADUR RAHMAN SOJIB',
    role: 'NIGHT GIRD',
    phone: '+8801885374041',
    email: '',
    photo: img5,
    mpoIndexNo: '-',
    joiningDate: '',
    fathersName: '',
    mothersName: '',
    contactNo: '+8801885374041',
    nationalIdNo: '',
    qualification: '',
    experience: '',
    interest: '',
    presentAddress: '',
    permanentAddress: '',
  },
];
export const getStaffById = (id) => SValue.find((s) => s.id === id);

