
import img12 from '/src/Images/12.jpg';
import img5 from '/src/Images/5.jpg';
import img6 from '/src/Images/6.jpg';
import img7 from '/src/Images/7.jpg';
import img8 from '/src/Images/8.jpg';
import img13 from '/src/Images/13.jpg';

export const TValue = [
  {
    id: 'md-abul-hashem',
    name: 'MD. ABUL HASHEM',
    role: 'Head Teacher',
    phone: '+8801885374041',
    email: 'bssyhet@yahoo.com',
    photo: img12,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'lila-banik',
    name: 'LILA BANIK',
    role: 'Senior Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img6,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'farhana-zannath',
    name: 'FARHANA ZANNATH',
    role: 'Senior Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img7,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'md-hamdu-miah',
    name: 'MD. HAMDU MIAH',
    role: 'Senior Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img8,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'mohammad-manik-miah',
    name: 'MOHAMMAD MANIK MIAH',
    role: 'Senior Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img5,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'musammat-rubina-akter',
    name: 'MUSAMMAT RUBINA AKTER',
    role: 'Senior Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img8,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'musammat-jafrin-sultana',
    name: 'MUSAMMAT JAFRIN SULTANA',
    role: 'Senior Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img5,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'hazera-begum',
    name: 'HAZERA BEGUM',
    role: 'Senior Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img12,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'papia-chowdhury',
    name: 'PAPIA CHOWDHURY',
    role: 'Senior Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img5,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'sharmin-sultana',
    name: 'SHARMIN SULTANA',
    role: 'Assistant Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img6,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'mitu-ranjan-talukdar',
    name: 'MITU RANJAN TALUKDAR',
    role: 'Assistant Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img7,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'perbez-mushraf',
    name: 'PERBEZ MUSHRAF',
    role: 'Senior Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img8,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'md-rubel-mia',
    name: 'MD. RUBEL MIA',
    role: 'Senior Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img5,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'ratna-datta-roy',
    name: 'RATNA DATTA ROY',
    role: 'Assistant Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img8,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
  {
    id: 'nazma-akhter',
    name: 'NAZMA AKHTER',
    role: 'Senior Teacher',
    phone: '+8801885374041',
    email: '',
    photo: img13,
    mpoIndexNo: '-',
    joiningDate: '04 Nov, 2018',
    fathersName: 'MD. YOUSUF ALI BHUIYAN',
    mothersName: 'SUNDARER MA',
    contactNo: '01718603386',
    nationalIdNo: '3624407262089',
    qualification: 'M.A. IN EDUCATION',
    experience: '-',
    interest: '-',
    presentAddress:
      'BLOCK - J, ROAD - 04, HOUSE - 17, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'RAYPUR, KENDUA, NETRAKONA',
  },
];

export const getTeacherById = (id) => TValue.find((t) => t.id === id);
