


export const EGValue = [
    {
    id: 'kanik-chandra-sharma',
    name: 'KANIK CHANDRA SHARMA',
    role: 'Chairman (2023 - 2024)',
    phone: '+8801885374041',
    email: '',
    photo: "/src/Images/5.jpg",
    mpoIndexNo: '-',
    joiningDate: '01 Jan, 2023',
    fathersName: 'RANA DASH',
    mothersName: 'BINA RANI DASH',
    contactNo: '+8801753487483',
    nationalIdNo: '7800845724',
    qualification: '8th CLASS',
    experience: '',
    interest: '',
    presentAddress: 'BADRUL MIAR BASA, GOTATIKOR, POST: KODOMTOLI, THANA: DAKKHIN SURMA, ZILLA: SYLHET',
    permanentAddress: 'VILL: SURJOPASHA, PO: SOMSERGONJBAZAR, THANA+ZILLA: MOULVIBAZAR',
  },
  {
    id: 'gonesh-sutradhar',
    name: 'GONESH SUTRADHAR',
    role: 'Member (2023 - 2024)',
    phone: '+8801885374041',
    email: '',
    photo: "/src/Images/6.jpg",
    mpoIndexNo: '-',
    joiningDate: '01 Jan, 2023',
    fathersName: 'ABUL BASHAR',
    mothersName: 'SAMSUN NAHAR',
    contactNo: '+8801885374041',
    nationalIdNo: '8670048449',
    qualification: 'MSc in Mathematics',
    experience: '',
    interest: '',
    presentAddress: 'Humayon Rashid Chattar, Sylhet',
    permanentAddress: 'Purba Jaflong, Gowainghat, Sylhet',
  },
  {
    id: 'md-abdul-kadir',
    name: 'MD. ABDUL KADIR',
    role: 'Member (2021 - 2022)',
    phone: '+8801885374041',
    email: '',
    photo: "/src/Images/7.jpg",
    mpoIndexNo: '-',
    joiningDate: '01 Jan, 2021',
    fathersName: '',
    mothersName: '',
    contactNo: '+8801885374041',
    nationalIdNo: '',
    qualification: '',
    experience: '',
    interest: '',
    presentAddress: '',
    permanentAddress: '',
  },
  {
    id: 'md-harunur-rashid',
    name: 'MD. HARUNUR RASHID',
    role: 'Member (2021 - 2022)',
    phone: '+8801885374041',
    email: 'hmdelwar2356@gmail.com',
    photo: "/src/Images/8.jpg",
    mpoIndexNo: '-',
    joiningDate: '01 Jan, 2021',
    fathersName: 'MOHAMMAD ABDUL JABBAR',
    mothersName: 'MAFIYA KHATUN',
    contactNo: '+8801885374041',
    nationalIdNo: '19791911875715436',
    qualification: 'B.COM',
    experience: '',
    interest: '',
    presentAddress: 'HOUSE NO:71, ROAD NO: 44, BLOCK: c, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'VILL: BARESWAR, POST: BARESWAR, P.S: BURICHONG, DIST: COMILA',
  },
  {
    id: 'kanik-chandra-sharma1',
    name: 'KANIK CHANDRA SHARMA',
    role: 'Chairman (2021 - 2022)',
    phone: '+8801885374041',
    email: '',
    photo: "/src/Images/7.jpg",
    mpoIndexNo: '-',
    joiningDate: '01 Jan, 2021',
    fathersName: 'RANA DASH',
    mothersName: 'BINA RANI DASH',
    contactNo: '+8801753487483',
    nationalIdNo: '7800845724',
    qualification: '8th CLASS',
    experience: '',
    interest: '',
    presentAddress: 'BADRUL MIAR BASA, GOTATIKOR, POST: KODOMTOLI, THANA: DAKKHIN SURMA, ZILLA: SYLHET',
    permanentAddress: 'VILL: SURJOPASHA, PO: SOMSERGONJBAZAR, THANA+ZILLA: MOULVIBAZAR',
  },
  {
    id: 'gonesh-sutradhar1',
    name: 'GONESH SUTRADHAR',
    role: 'Member (2021 - 2022)',
    phone: '+8801885374041',
    email: '',
    photo: "/src/Images/8.jpg",
    mpoIndexNo: '-',
    joiningDate: '01 Jan, 2021',
    fathersName: 'ABUL BASHAR',
    mothersName: 'SAMSUN NAHAR',
    contactNo: '+8801885374041',
    nationalIdNo: '8670048449',
    qualification: 'MSc in Mathematics',
    experience: '',
    interest: '',
    presentAddress: 'Humayon Rashid Chattar, Sylhet',
    permanentAddress: 'Purba Jaflong, Gowainghat, Sylhet',
  },
  {
    id: 'md-abdul-kadir1',
    name: 'MD. ABDUL KADIR',
    role: 'Member (2019 - 2020)',
    phone: '+8801885374041',
    email: '',
    photo: "/src/Images/5.jpg",
    mpoIndexNo: '-',
    joiningDate: '08 Jan, 2019',
    fathersName: '',
    mothersName: '',
    contactNo: '+8801885374041',
    nationalIdNo: '',
    qualification: '',
    experience: '',
    interest: '',
    presentAddress: '',
    permanentAddress: '',
  },
  {
    id: 'md-harunur-rashid1',
    name: 'MD. HARUNUR RASHID',
    role: 'Member (2021 - 2022)',
    phone: '+8801885374041',
    email: 'hmdelwar2356@gmail.com',
    photo: "/src/Images/6.jpg",
    mpoIndexNo: '-',
    joiningDate: '08 Jan, 2021',
    fathersName: 'MOHAMMAD ABDUL JABBAR',
    mothersName: 'MAFIYA KHATUN',
    contactNo: '+8801885374041',
    nationalIdNo: '19791911875715436',
    qualification: 'B.COM',
    experience: '',
    interest: '',
    presentAddress: 'HOUSE NO:71, ROAD NO: 44, BLOCK: c, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'VILL: BARESWAR, POST: BARESWAR, P.S: BURICHONG, DIST: COMILA',
  },
];
export const getExCommitteeById = (id) => EGValue.find((eg) => eg.id === id);

