


export const GValue = [
    {
    id: 'kanik-chandra-sharma',
    name: 'KANIK CHANDRA SHARMA',
    role: 'Chairman',
    phone: '+8801885374041',
    email: '',
    photo: "/src/Images/5.jpg",
    mpoIndexNo: '-',
    joiningDate: '03 Aug, 2008',
    fathersName: 'RANA DASH',
    mothersName: 'BINA RANI DASH',
    contactNo: '+8801753487483',
    nationalIdNo: '7800845724',
    qualification: '8th CLASS',
    experience: '',
    interest: '',
    presentAddress: 'BADRUL MIAR BASA, GOTATIKOR, POST: KODOMTOLI, THANA: DAKKHIN SURMA, ZILLA: SYLHET',
    permanentAddress: 'VILL: SURJOPASHA, PO: SOMSERGONJBAZAR, THANA+ZILLA: MOULVIBAZAR',
  },
  {
    id: 'gonesh-sutradhar',
    name: 'GONESH SUTRADHAR',
    role: 'Member',
    phone: '+8801885374041',
    email: '',
    photo: "/src/Images/6.jpg",
    mpoIndexNo: '-',
    joiningDate: '16 Jan, 2024',
    fathersName: 'ABUL BASHAR',
    mothersName: 'SAMSUN NAHAR',
    contactNo: '+8801885374041',
    nationalIdNo: '8670048449',
    qualification: 'MSc in Mathematics',
    experience: '',
    interest: '',
    presentAddress: 'Humayon Rashid Chattar, Sylhet',
    permanentAddress: 'Purba Jaflong, Gowainghat, Sylhet',
  },
  {
    id: 'md-abdul-kadir',
    name: 'MD. ABDUL KADIR',
    role: 'Member',
    phone: '+8801885374041',
    email: '',
    photo: "/src/Images/7.jpg",
    mpoIndexNo: '-',
    joiningDate: '',
    fathersName: '',
    mothersName: '',
    contactNo: '+8801885374041',
    nationalIdNo: '',
    qualification: '',
    experience: '',
    interest: '',
    presentAddress: '',
    permanentAddress: '',
  },
  {
    id: 'md-harunur-rashid',
    name: 'MD. HARUNUR RASHID',
    role: 'Member',
    phone: '+8801885374041',
    email: 'hmdelwar2356@gmail.com',
    photo: "/src/Images/8.jpg",
    mpoIndexNo: '-',
    joiningDate: '28 Feb, 2004',
    fathersName: 'MOHAMMAD ABDUL JABBAR',
    mothersName: 'MAFIYA KHATUN',
    contactNo: '+8801885374041',
    nationalIdNo: '19791911875715436',
    qualification: 'B.COM',
    experience: '',
    interest: '',
    presentAddress: 'HOUSE NO:71, ROAD NO: 44, BLOCK: c, SHAHJALAL UPOSHOHOR, SYLHET',
    permanentAddress: 'VILL: BARESWAR, POST: BARESWAR, P.S: BURICHONG, DIST: COMILA',
  },
];
export const getCommitteeById = (id) => GValue.find((g) => g.id === id);

